version: '3.8'

services:
  dataanalysis:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    container_name: data-trend-analysis